"""Pydantic schema package."""

from app.schemas.api_key import (
    APIKeyBase,
    APIKeyCreateRequest,
    APIKeyCreateResponse,
    APIKeyResponse,
    APIKeySelfTestResponse,
    APIKeyStatus,
)
from app.schemas.admin import (
    AdminDetectionDetailResponse,
    AdminDetectionListItem,
    AdminDetectionListResponse,
    AdminDetectionMini,
    AdminOverviewGranularity,
    AdminOverviewPeriod,
    AdminOverviewPreset,
    AdminOverviewResponse,
    AdminOverviewSeriesItem,
    AdminOverviewSummary,
    AdminRecentDetectionItem,
    AdminRecentUserItem,
    AdminStatusResponse,
    AdminUserCreditsAdjustRequest,
    AdminUserCreditsAdjustResponse,
    AdminUserDetailResponse,
    AdminUserListItem,
    AdminUserListResponse,
    AdminUserProfile,
    AdminUserUpdateRequest,
)
from app.schemas.analysis import AnalysisResponse, Citation, DetectRequest, SentenceAnalysis
from app.schemas.parse_files import ParseFilesResponse, ParsedFileResult
from app.schemas.report import ReportPdfContent, ReportPdfRequest
from app.schemas.scan_example import ScanExamplesResponse, ScanHeroExampleItem, ScanUsageExampleItem
from app.schemas.detection import DetectionItem, DetectionListResponse, DetectionRequest, DetectionResponse
from app.schemas.quota import QuotaResponse
from app.schemas.auth import GuestTokenRequest, LoginRequest, RegisterRequest, Token, TokenPayload
from app.schemas.responses import DatabasePingResponse, ErrorResponse, HealthResponse, ReadinessResponse, WelcomeResponse
from app.schemas.user import UserBase, UserCreate, UserProfile, UserProfileUpdate, UserResponse
from app.schemas.team import (
    TeamCreateRequest,
    TeamMemberCreateRequest,
    TeamMemberResponse,
    TeamResponse,
    TeamStatsItem,
    TeamStatsResponse,
)
from app.core.roles import UserRole

__all__ = [
    "APIKeyBase",
    "APIKeyCreateRequest",
    "APIKeyCreateResponse",
    "APIKeyResponse",
    "APIKeySelfTestResponse",
    "APIKeyStatus",
    "AdminDetectionDetailResponse",
    "AdminDetectionListItem",
    "AdminDetectionListResponse",
    "AdminDetectionMini",
    "AdminOverviewGranularity",
    "AdminOverviewPeriod",
    "AdminOverviewPreset",
    "AdminOverviewResponse",
    "AdminOverviewSeriesItem",
    "AdminOverviewSummary",
    "AdminRecentDetectionItem",
    "AdminRecentUserItem",
    "AdminStatusResponse",
    "AdminUserCreditsAdjustRequest",
    "AdminUserCreditsAdjustResponse",
    "AdminUserDetailResponse",
    "AdminUserListItem",
    "AdminUserListResponse",
    "AdminUserProfile",
    "AdminUserUpdateRequest",
    "AnalysisResponse",
    "Citation",
    "GuestTokenRequest",
    "DetectionItem",
    "DetectionListResponse",
    "DetectionRequest",
    "DetectionResponse",
    "DetectRequest",
    "QuotaResponse",
    "ReportPdfContent",
    "ReportPdfRequest",
    "DatabasePingResponse",
    "ErrorResponse",
    "HealthResponse",
    "ReadinessResponse",
    "LoginRequest",
    "RegisterRequest",
    "TeamCreateRequest",
    "TeamMemberCreateRequest",
    "TeamMemberResponse",
    "TeamResponse",
    "TeamStatsItem",
    "TeamStatsResponse",
    "Token",
    "TokenPayload",
    "SentenceAnalysis",
    "ParseFilesResponse",
    "ParsedFileResult",
    "ScanExamplesResponse",
    "ScanHeroExampleItem",
    "ScanUsageExampleItem",
    "UserBase",
    "UserCreate",
    "UserProfile",
    "UserProfileUpdate",
    "UserResponse",
    "UserRole",
    "WelcomeResponse",
]
